import Head from "next/head";
import MainPage from "../components/bodyArticle/MainPage";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="bg-gradient-to-r from-violet-700 to-cyan-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>Pizza Joint</Navbar>

      <MainPage />
    </div>
  );
}
